services:
    grammy:
        container_name: grammy
        build:
            context: ./grammy
            dockerfile: Dockerfile.dev
        restart: always
        depends_on:
            - database
        volumes:
            - $PWD/grammy:/app
        ports:
            - 5555:5555
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
            - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN

    database:
        container_name: database
        image: postgres
        restart: always
        volumes:
            - $PWD/database:/data/db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
