services:
    grammy:
        container_name: grammy
        build:
            context: ./grammy
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - database
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
            - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
            - ADMIN_PASSWORD=$ADMIN_PASSWORD

    database:
        container_name: database
        image: postgres
        restart: always
        volumes:
            - $PWD/dbs:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
